# my bashrc personalisations 
# add this to the end of the actual .bashrc
#
#
# for FILE in ~/.bashrcdir/*; do
#     source $FILE
# done



alias ls="ls -lh"
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias update="sudo apt update && sudo apt upgrade"


[ -d "$HOME/.local/scripts" ] && export PATH="$PATH:$HOME/.local/scripts"
