#!/bin/bash

last_state=""

# Function to count number of *connected* displays
get_connected_displays() {
    xrandr | grep " connected" | wc -l
}

# Function to apply scaling based on number of displays
apply_scaling() {
    local count
    count=$(get_connected_displays)

    if [ "$count" -gt 1 ]; then
        # External display connected
        gsettings set org.gnome.desktop.interface text-scaling-factor 1
        echo "$(date): External display detected, scaling set to 1"
    else
        # Only built-in display
        gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
        echo "$(date): Only internal display, scaling set to 1.2"
    fi
}

while true; do
    new_state=$(xrandr | grep " connected")

    if [[ "$new_state" != "$last_state" ]]; then
        apply_scaling
        last_state="$new_state"
    fi

    sleep 2
done
